
/*------------------------------------------------------------------------
    File        : Directions
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : mam
    Created     : Wed Aug 21 14:53:11 CEST 2024
    Notes       : 
  ----------------------------------------------------------------------*/

ENUM Tmp.Directions :  

        DEFINE ENUM 
                    Toutes = 0
                    DEFAULT = Toutes
                    Nord = 1
                    NordEtEst = 2
                    Ouest = 3
                    SudEtOuest = 4
                    Sud = 5
                    SudEtEst = 6
                    Est = 7    
                    NordEtOuest = 8.

END ENUM.